### PR TITLE
Update entitlement.plist

### PR DESCRIPTION
**Pull request by anignatev**

### CODE REVIEW

**Comment by Tabiskabis** [comment]
This should fix the inability to load pkcs#11 providers?

**Comment by chris2511** [comment]
```
Disable Library Validation Entitlement
A Boolean value that indicates whether the app loads arbitrary plug-ins or frameworks,
without requiring code signing.
```
Indeed, why is it necessary to disable it?
Your commit message is too sparse to justify a security change.

**Comment by linusklan** [comment]
Hi chris2511.

I also think "Disable Library Validation Entitlement" is good option for Xca.

Enabling Library Validation Entitlement is only good if your application does not load any libraries other than those you put when building the installer.

xca works by loading an external pkcs11 library not written and signed by you.

I am the author of the polish id library, I can't sign it with the smartcard option because it won't work in firefox because firefox is not signed to use the smartcard.

Do you think firefox should be signed to use the smard card since it doesn't use it, Just so that the pkcs11 module can use it?.

macOS is crazy.

**Comment by chris2511** [comment]
First of all thanks for the justification for this I change. I will use parts of it in modified form for
the commit message.

Do you suggest adding
```
<key>com.apple.security.smartcard</key>
<true/>
```
to the `entitlement.plist` should also be done?
I once started appstore-compliance for XCA, but it accesses files outside the permitted directory, so I stopped that attempt.
But the entitlement.plist is still there and maybe I'll give it another try in the future....

**Comment by linusklan** [comment]
Yes,  a lot of pkcs11 modules use smart cards.

**Comment by chris2511** [comment]
Merged differently

**Pull request closed without merging**
