### PR TITLE
Fixed german typos

### PR DESCRIPTION
**Pull request by botboe**
I fixed some smaller german typos.

### CODE REVIEW

**Comment by Erfankam** [comment]
@botboe Thanks you for contributions. Would I suggest some improvements in German translation?
I would like to refer to "Persian" word translation in German that left intact without translation in Datei->Sprache->Persian. Persian is used instead of "Persisch".

**Comment by botboe** [comment]
@Erfankam the translation-file is ok:
image

So it might be an application-problem.

**Comment by chris2511** [comment]
> @botboe Thanks you for contributions. Would I suggest some improvements in German translation? I would like to refer to "Persian" word translation in German that left intact without translation in Datei->Sprache->Persian. Persian is used instead of "Persisch".

The menu-list of languages contains the translated-to-current-language version and the original english expression in parenthesis. And the native name of the language as pop-up.

The translation to german as "Persisch" is Ok

**Comment by botboe** [comment]
@chris2511 done!

**Comment by Erfankam** [comment]
Thanks all for quick answer. But I m still seeing this in the last version while I am building from source:

image

**Comment by Erfankam** [comment]
> @Erfankam the translation-file is ok: image
> 
> So it might be an application-problem.

@botboe  Thanks for the evidence. But where is the problem? I am afraid maybe I am wrong or make a mistake in launching application? :)

**Comment by chris2511** [comment]
> Thanks all for quick answer. But I m still seeing this in the last version while I am building from source:
> 

Did you build this branch ?
https://github.com/botboe/xca/tree/patch-1

The PR is not yet merged

**Comment by botboe** [comment]
@chris2511 this wasn't fixed by me as it is already correct in your main branch!

https://github.com/chris2511/xca/blob/main/lang/xca_de.ts#L1451

**Comment by Erfankam** [comment]
The issue is still exist in my environment, even after updating to last version of Git. But I found out that this issue is exist for all other languages too. E.g. for the French language. I mean all other languages are showing wrong translation of Persian in the menu.
So, maybe the problem is Persian TSfile or application code.

**Comment by Erfankam** [comment]
The point is that this problem is not exist in Windows platform at all. As you can see bellow, All translations are correct in German.
lang-issue-persian

**Comment by chris2511** [comment]
On linux xca takes the translation files from the default installation locations.
You need to `sudo make install` / `sudo cmake --build builddir -t install` to put the translations in place
or copy them manually to  "/usr/local/share/xca/i18n/" or  "/usr/share/xca/i18n/"

**Comment by Erfankam** [comment]
After installing by cmake, I have no problem in translations even in the Linux. Thanks.

**Pull request merged**
