### PR TITLE
Allow for generating keys of 8192 bits in size

### PR DESCRIPTION
**Pull request by jasperla**
I've verified this generates correct and working keys.

### CODE REVIEW

**Comment by chris2511** [comment]
You know that keys of any reasonable size can be generated by entering the size manually into the input box?
Described in the manual: https://hohnstaedt.de/xca-doc/xca-7.html#ss7.1

**Comment by jasperla** [comment]
I did not know that actually, maybe it's my fault but the dialog does not indicate this possibility.

Also, input validation does correctly deny `-1` but accepts any other value and hands it off to OpenSSL, including `0`.
This then results in an OpenSSL error message that isn't very clear:
0: `RSA_BUILTIN_KEYGEN:key size too small`
2147483646: Accepted at first, but then fails: `BN_EXPAND_INTERNAL: bignum too long`
2147483647: `RSA_BUILTIN_KEYGEN:key size too small`

So perhaps add 8k to the list of suggested sizes, add a note to the dialog making it clear one can enter arbitrary key lengths and apply more strict input validation?

**Comment by chris2511** [comment]
There is already a validation, refusing values > 0 and < 32 bit, because they will result in an OpenSSL error and are likely a typo. The 0 slipped through. Will add a patch to catch it.
Insane values < 1024 and > 8192 must be approved by clicking away another message box.
This should be sufficient for sane users, I think.

**Comment by jasperla** [comment]
Thanks :)

**Pull request merged**
